version: '3.2'

services:

  #nginx:
    #build: ./src/nginx
    #links:
      #- inventory-service:inventory-service
      #- billing-service:billing-service
    #ports:
      #- "80:80"

  inventory-service:
    build:
      context: ./src/InventoryService
    container_name: inventory-service
    ports:
      - "8000:80"
    depends_on:
      - mysql

  billing-service:
    build:
      context: ./src/BillingService
    container_name: billing-service
    ports:
      - "8001:80"
    depends_on:
      - redis
    networks:
      - app-net

  message-queue:
    image: nats
    container_name: message-queue
    ports:
      - "4222:4222"
    networks:
      - app-net

    #environment:
      #- "Endpoints:Backend=http://inventory-service:80"    
    #depends_on:
      #- inventory-service

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword

  redis:
    #image: redis:3.2.100-nanoserver
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  #redis:
    #build:
      #context: ./src/Redis
    #container_name: redis-server
    #ports:
      #- "6379:6379"

networks:
  app-net:
    driver: bridge